### ISSUE TITLE
Use the Claude 3 models from Anthropic in VertexAI with langchain

### ISSUE THREAD

**Issue by romaintoub** [langchain-ai/langchain-google#109]
Hello!

I'd like to use langchain with the Claude models from Anthropic coming from [Vertex AI](https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-claude).

To leverage these models in Python, we have to use a function from anthropic called `AnthropicVertex` but this cannot be integrated as a langchain model.
AFAIK we cannot bring the Claude models from langchain-anthropic as the auth method is different: https://github.com/langchain-ai/langchain/tree/master/libs/partners/anthropic

Could this be created here with the `VertexAI` function? Or is there any alternative to bring this model with langchain?

Thank you!

**Comment by lkuligin** [comment]
Yes, we should add them with requiring an extra dependency.
I've added a first implementation (it doesn't support tools yet), if you'd like to contribute, that would be awesome.

**Comment by romaintoub** [comment]
amazing, thank you!
