### ISSUE TITLE
CallbackHandler on_llm_new_token method not fire with ChatGoogleGenerativeAI(Gemini) but works fine with ChatOpenAI when streaming true

### ISSUE THREAD

**Issue by hasansustcse13** [langchain-ai/langchain-google#120]
### System Info

aiohttp==3.9.1
aiosignal==1.3.1
annotated-types==0.6.0
anyio==4.1.0
attrs==23.1.0
cachetools==5.3.2
certifi==2023.11.17
charset-normalizer==3.3.2
colorama==0.4.6
dataclasses-json==0.6.3
frozenlist==1.4.0
google-ai-generativelanguage==0.4.0
google-api-core==2.15.0
google-auth==2.25.2
google-generativeai==0.3.1
googleapis-common-protos==1.62.0
greenlet==3.0.2
grpcio==1.60.0
grpcio-status==1.60.0
idna==3.6
jsonpatch==1.33
jsonpointer==2.4
langchain-community==0.0.3
langchain-core==0.1.0
langchain-google-genai==0.0.3
langsmith==0.0.70
marshmallow==3.20.1
multidict==6.0.4
mypy-extensions==1.0.0
numpy==1.26.2
packaging==23.2
Pillow==10.1.0
proto-plus==1.23.0
protobuf==4.25.1
pyasn1==0.5.1
pyasn1-modules==0.3.0
pydantic==2.5.2
pydantic_core==2.14.5
PyYAML==6.0.1
requests==2.31.0
rsa==4.9
sniffio==1.3.0
SQLAlchemy==2.0.23
tenacity==8.2.3
tqdm==4.66.1
typing-inspect==0.9.0
typing_extensions==4.9.0
urllib3==2.1.0
yarl==1.9.4

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from typing import Any, Optional
from uuid import UUID

from langchain.chains import LLMChain
from langchain_community.chat_models import ChatOpenAI
from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.outputs import LLMResult
from langchain_core.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

prompt_template = "Tell me details about the Company {name} with 2 bullet point?"


class StreamingLLMCallbackHandler(BaseCallbackHandler):

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        print(token, end='')

    def on_llm_end(self, response: LLMResult, *, run_id: UUID, parent_run_id: Optional[UUID] = None, **kwargs: Any) -> Any:
        print('\n\n---------------------LLM_END--------------------------')
        print(response.generations[0][0].text)


def gemini_stream_with_cb():
    llm = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key='AIzaSPVggdfgerweselzbVCHH', streaming=True, callbacks=[StreamingLLMCallbackHandler()])
    llm_chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template(prompt_template), verbose=True)
    llm_chain.run(name="Google")


def openai_stream_with_cb():
    llm = ChatOpenAI(openai_api_key='sk-pSHx9qACbzdgsdgyuuyNCXpZ0', model='gpt-4', streaming=True, callbacks=[StreamingLLMCallbackHandler()])
    llm_chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template(prompt_template), verbose=True)
    llm_chain.run(name="Open AI")


if __name__ == '__main__':
    gemini_stream_with_cb()
    # openai_stream_with_cb()

```

**ChatGoogleGenerativeAI:** on_llm_new_token not triggered, but on_llm_end triggered
**ChatOpenAI**: Both triggered

### Expected behavior

 **on_llm_new_token should trigger for ChatGoogleGenerativeAI**

**Comment by efriis** [comment]
@lkuligin I think this is still an issue

**Comment by sglebs** [comment]
I am having the same issue. I plug a callback handler and it does not get called on tokens. But it works with the OpenAI equivalent. I am using:

langchain==0.1.20
langchain-google-genai==1.0.4
langchain-google-vertexai==1.0.4

**Comment by lkuligin** [comment]
with the "proper" wait to invoke streaming everything seems to work fine:
```
from typing import Any
from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.outputs import LLMResult
from langchain_core.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI


class StreamingLLMCallbackHandler(BaseCallbackHandler):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.tokens = []
        self.generations = []

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        self.tokens.append(token)

    def on_llm_end(self, response: LLMResult, **kwargs: Any) -> Any:
        self.generations.append(response.generations[0][0].text)


def test_streaming_callback() -> None:
    prompt_template = "Tell me details about the Company {name} with 2 bullet point?"
    cb = StreamingLLMCallbackHandler()
    llm = ChatGoogleGenerativeAI(model="gemini-pro", callbacks=[cb])
    llm_chain = PromptTemplate.from_template(prompt_template) | llm
    for t in llm_chain.stream({"name": "Google"}):
        pass
    assert len(cb.tokens) > 1
    assert len(cb.generations) == 1
```

**Comment by dharless-eli-lilly** [comment]
> I am having the same issue. I plug a callback handler and it does not get called on tokens. But it works with the OpenAI equivalent. I am using:
> 
> langchain==0.1.20 langchain-google-genai==1.0.4 langchain-google-vertexai==1.0.4

I'm having the problem still with slightly updated versions. Did you happen to get it working?

**Comment by sglebs** [comment]
> > I am having the same issue. I plug a callback handler and it does not get called on tokens. But it works with the OpenAI equivalent. I am using:
> > langchain==0.1.20 langchain-google-genai==1.0.4 langchain-google-vertexai==1.0.4
> 
> I'm having the problem still with slightly updated versions. Did you happen to get it working?

no. maybe if newer versions of the libs?

**Comment by RushikeshKothawade07** [comment]
> ### System Info
> aiohttp==3.9.1 aiosignal==1.3.1 annotated-types==0.6.0 anyio==4.1.0 attrs==23.1.0 cachetools==5.3.2 certifi==2023.11.17 charset-normalizer==3.3.2 colorama==0.4.6 dataclasses-json==0.6.3 frozenlist==1.4.0 google-ai-generativelanguage==0.4.0 google-api-core==2.15.0 google-auth==2.25.2 google-generativeai==0.3.1 googleapis-common-protos==1.62.0 greenlet==3.0.2 grpcio==1.60.0 grpcio-status==1.60.0 idna==3.6 jsonpatch==1.33 jsonpointer==2.4 langchain-community==0.0.3 langchain-core==0.1.0 langchain-google-genai==0.0.3 langsmith==0.0.70 marshmallow==3.20.1 multidict==6.0.4 mypy-extensions==1.0.0 numpy==1.26.2 packaging==23.2 Pillow==10.1.0 proto-plus==1.23.0 protobuf==4.25.1 pyasn1==0.5.1 pyasn1-modules==0.3.0 pydantic==2.5.2 pydantic_core==2.14.5 PyYAML==6.0.1 requests==2.31.0 rsa==4.9 sniffio==1.3.0 SQLAlchemy==2.0.23 tenacity==8.2.3 tqdm==4.66.1 typing-inspect==0.9.0 typing_extensions==4.9.0 urllib3==2.1.0 yarl==1.9.4
> 
> ### Who can help?
> _No response_
> 
> ### Information
> * [ ]  The official example notebooks/scripts
> * [ ]  My own modified scripts
> 
> ### Related Components
> * [ ]  LLMs/Chat Models
> * [ ]  Embedding Models
> * [ ]  Prompts / Prompt Templates / Prompt Selectors
> * [ ]  Output Parsers
> * [ ]  Document Loaders
> * [ ]  Vector Stores / Retrievers
> * [ ]  Memory
> * [ ]  Agents / Agent Executors
> * [ ]  Tools / Toolkits
> * [ ]  Chains
> * [ ]  Callbacks/Tracing
> * [ ]  Async
> 
> ### Reproduction
> ```
> from typing import Any, Optional
> from uuid import UUID
> 
> from langchain.chains import LLMChain
> from langchain_community.chat_models import ChatOpenAI
> from langchain_core.callbacks import BaseCallbackHandler
> from langchain_core.outputs import LLMResult
> from langchain_core.prompts import PromptTemplate
> from langchain_google_genai import ChatGoogleGenerativeAI
> 
> prompt_template = "Tell me details about the Company {name} with 2 bullet point?"
> 
> 
> class StreamingLLMCallbackHandler(BaseCallbackHandler):
> 
>     def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
>         print(token, end='')
> 
>     def on_llm_end(self, response: LLMResult, *, run_id: UUID, parent_run_id: Optional[UUID] = None, **kwargs: Any) -> Any:
>         print('\n\n---------------------LLM_END--------------------------')
>         print(response.generations[0][0].text)
> 
> 
> def gemini_stream_with_cb():
>     llm = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key='AIzaSPVggdfgerweselzbVCHH', streaming=True, callbacks=[StreamingLLMCallbackHandler()])
>     llm_chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template(prompt_template), verbose=True)
>     llm_chain.run(name="Google")
> 
> 
> def openai_stream_with_cb():
>     llm = ChatOpenAI(openai_api_key='sk-pSHx9qACbzdgsdgyuuyNCXpZ0', model='gpt-4', streaming=True, callbacks=[StreamingLLMCallbackHandler()])
>     llm_chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template(prompt_template), verbose=True)
>     llm_chain.run(name="Open AI")
> 
> 
> if __name__ == '__main__':
>     gemini_stream_with_cb()
>     # openai_stream_with_cb()
> ```
> 
> **ChatGoogleGenerativeAI:** on_llm_new_token not triggered, but on_llm_end triggered **ChatOpenAI**: Both triggered
> 
> ### Expected behavior
> **on_llm_new_token should trigger for ChatGoogleGenerativeAI**

same issue, can someone help fix it?
how to use map reduce chain type with gemini models using chatgooglegenerativeai and also get streaming responses at the same time using custom callback handler where I want token level streaming by appending in a queue

**Comment by dharless-eli-lilly** [comment]
I had to pass `llm_args={"stream": True}` when creating my `LLMChain`. There is a difference in the way the `streaming` field is handled on `ChatVertexAI` vs other providers I believe

**Comment by hasansustcse13** [comment]
`LLMChain` is deprecated. If you want to stream and also get the data in `on_llm_new_token ` you have to use `LangChain Expression Language (LCEL)` way. To create any LCEL chain from legacy chain you need to go through the code base and understand how does legacy chain work internally and then build LCEL chain from it if langchain doesn't provide LCEL chain. You can find some insights here. 

https://python.langchain.com/v0.1/docs/expression_language/
https://python.langchain.com/v0.1/docs/modules/chains/
https://python.langchain.com/v0.2/docs/tutorials/rag/
How does LCEL build using Pipe (Or Operator):
https://www.youtube.com/watch?v=O0dUOtOIrfs

CC: @dharless-eli-lilly @sglebs @RushikeshKothawade07

**Comment by dharless-eli-lilly** [comment]
Thanks @hasansustcse13! Fwiw the workaround I posted works for me - it streams asynchronously and triggers the callbacks properly. Though to your point it is deprecated so hopefully we get the time to refactor soon.
