### ISSUE TITLE
Vertex AI [feature]: Support JSON Mode for Gemini

### ISSUE THREAD

**Issue by afirstenberg** [langchain-ai/langchain-google#144]
See documentation for `responseMimeType` at https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini#request_body

See https://github.com/langchain-ai/langchainjs/issues/5071

**Comment by Ben81828** [comment]
Is it possible to pass in our defined schema and specify the use of json_mode, like in this example?
https://python.langchain.com/v0.1/docs/modules/model_io/chat/structured_output/

```python
structured_llm = model.with_structured_output(Joke, method="json_mode")
```
