### ISSUE TITLE
Kaggle default metadata is list but your default metadata is tuple (google api key matching issue) [bug]

### ISSUE THREAD

**Issue by gunjak** [langchain-ai/langchain-google#158]
I have found a bug while matching api key on kaggle.

![kaggle_issues](https://github.com/langchain-ai/langchain-google/assets/90557288/49a88ff6-3cd3-415c-b445-970e794b8135)
### **This is the  getting error on kaggle notebook**<br>

![langchain_issue](https://github.com/langchain-ai/langchain-google/assets/90557288/4ba8596a-7472-4212-8819-f8d82b550fef)
 ### Here defualt metadata is tuple datatype <br>

![Kaggle_git_issues](https://github.com/langchain-ai/langchain-google/assets/90557288/5f907da8-33dc-46d9-a00b-bd3943f4aa69)
 ###Here default metadata is of list datatype <br>

**May I fix this issue?** Thanks

**Comment by lkuligin** [comment]
Sure, please feel free to send a PR to fix this!

**Comment by gunjak** [comment]
I have tried another models on the kaggle but they are also not working. Does **langchain_google_genai** models not for kaggle because models are working in google colab but not on kaggle??

**Comment by gunjak** [comment]
By review code I found that there is bug from kaggle side. I There metadata should be of tuple type because google model is accepting tuple type. So I have raised issue but did not got response.
