### ISSUE TITLE
[Feature Request] Support for MatchingEngineIndexEndpoint Properties

### ISSUE THREAD

**Issue by tdigangi** [langchain-ai/langchain-google#202]
There are several properties in aiplatform.MatchingEngineIndexEndpoint that are not supported in langchain-google. These need to be added for support in the VectorSearchVectorStore.from_components() method. The more critical properties for enterprise adoption are the private-service-connect properties shown below.

- [private-service-connect](https://cloud.google.com/vertex-ai/docs/vector-search/setup/private-service-connect)
- [MatchingEngineIndexEndpoint_private_service_connect_ip_address](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.MatchingEngineIndexEndpoint#google_cloud_aiplatform_MatchingEngineIndexEndpoint_private_service_connect_ip_address)

**Comment by tdigangi** [comment]
I have added a [langchain-google PR ](https://github.com/langchain-ai/langchain-google/pull/203)to start this incorporation please let me know how to proceed.

**Comment by lkuligin** [comment]
please, feel free to send a PR with any other properties you feel are useful.

**Comment by tdigangi** [comment]
Closed with https://github.com/langchain-ai/langchain-google/pull/203
