### ISSUE TITLE
[Feature Request] Support for Gemini RAG API

### ISSUE THREAD

**Issue by mands** [langchain-ai/langchain-google#204]
Would be great to have support for the RAG API documented at https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/rag-api and exposed within the `vertex.preview.rag` module in the python SDK.

**Comment by lkuligin** [comment]
If I'm not mistaken, it's LLamaIndex API so it's an alternative framework for orchestrating genAI applications.
