### ISSUE TITLE
Add Google Drive integration

### ISSUE THREAD

**Issue by pprados** [langchain-ai/langchain-google#220]
Hello,

I propose a [langchain Google Drive](https://github.com/pprados/langchain-googledrive) integration.
May be, we can merge our projects.

**Comment by lkuligin** [comment]
sounds great, please, feel free to raise a PR (maybe splitting into smaller ones would be a good idea)!

**Comment by pprados** [comment]
Another approach would be for Google to also be the administrator of langchain-googledrive.
I'm open to it. What do you think? The PR could be very big.

**Comment by pprados** [comment]
@lkuligin 
I'm afraid that if I give you the source, I won't be able to change it without waiting for your approval.
What would be the best approach for Google to take partial responsibility for this component, and for me to be able to simply contribute to it?

**Comment by pprados** [comment]
Allo @lkuligin ?

**Comment by lkuligin** [comment]
I'm sorry but I'm not sure we can commit to take responsibility for any other components. Let's try to keep this integration a light-weighted, and I'm happy to add a notice to a docsting about existing richer one (with a dislaimer that is't open-source).

**Comment by pprados** [comment]
I understand. My proposal is open source. I invite you to suggest PRs ;-)

**Comment by pprados** [comment]
If you have any contacts at Google Workspace, please don't hesitate to contact me.
