### ISSUE TITLE
VertexAI: can't use tool_choice (forced tool calls) on gemini-preview

### ISSUE THREAD

**Issue by tognee** [langchain-ai/langchain-google#261]
The issue is with this line here:
https://github.com/langchain-ai/langchain-google/blob/libs/vertexai/v1.0.4/libs/vertexai/langchain_google_vertexai/chat_models.py#L1140

Has been fixed with this PR: https://github.com/langchain-ai/langchain-google/pull/241

Still waiting for a new release with the fix (https://github.com/langchain-ai/langchain-google/pull/249 is working on that)

**Comment by lkuligin** [comment]
We're planning the release early next week.
