### ISSUE TITLE
Message `name` parameter should be populated with Message.author

### ISSUE THREAD

**Issue by efriis** [langchain-ai/langchain-google#34]
https://ai.google.dev/api/python/google/ai/generativelanguage/Message

Will need to bump langchain-core minimum version to 0.1.26 in order to make sure BaseMessage.name attribute exists

**Comment by lkuligin** [comment]
@monicamilan pls, take a look

**Comment by efriis** [comment]
Oh I also realized this isn't a feature of gemini models, so probably not that relevant! Feel free to close unless relevant for another reason
