### ISSUE TITLE
Include 'finish_reason' in ChatVertexAI response_metadata

### ISSUE THREAD

**Issue by michaelchia** [langchain-ai/langchain-google#351]
I would like to be able to inspect the 'finish_reason' from the output response of ChatVertexai.

Probably requires slight modification of `langchain_google_vertexai._utils.get_generation_info`.

**Comment by lkuligin** [comment]
@michaelchia would you be open to send a PR, please?

**Comment by michaelchia** [comment]
sure gladly. i'll try find time within the next few days
