### ISSUE TITLE
TypeError: Additional kwargs key generation_token_count already exists in left dict and value has unsupported type <class 'int'>.

### ISSUE THREAD

**Issue by Sai-Jahnavi-Bachu** [langchain-ai/langchain-google#354]
Hey guys, I am trying out the sample code given in langchain doc, when executing it getting an error

**raise TypeError(
TypeError: Additional kwargs key generation_token_count already exists in left dict and value has unsupported type <class 'int'>.**

This is the code, 
from langchain.agents import AgentExecutor, create_tool_calling_agent, tool
from langchain_aws import ChatBedrock
from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a helpful assistant"),
        ("placeholder", "{chat_history}"),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),
    ]
)
model = ChatBedrock(
    model_id="meta.llama3-70b-instruct-v1:0"
)

@tool
def magic_function(input: int) -> int:
    """Applies a magic function to an input."""
    return input + 2

tools = [magic_function]

agent = create_tool_calling_agent(model, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

agent_executor.invoke({"input": "what is the value of magic_function(3)?"})

# Using with chat history
from langchain_core.messages import AIMessage, HumanMessage
agent_executor.invoke(
    {
        "input": "what's my name?",
        "chat_history": [
            HumanMessage(content="hi! my name is bob"),
            AIMessage(content="Hello Bob! How can I assist you today?"),
        ],
    }
)

can anyone help me out?

**Comment by lkuligin** [comment]
ChatBedrock is not part of this library, please, ask in another github repo.
