### ISSUE TITLE
GoogleDriveLoader hardcodes the Scope to a restricted scope

### ISSUE THREAD

**Issue by walterheck** [langchain-ai/langchain-google#422]
Currently the GoogleDriveLoader hardcodes the scope to a restricted scope, which means in order to use this in production an extremely heavy security review by google is needed (several weeks long): https://developers.google.com/drive/api/guides/api-specific-auth

Instead, I'd like to be able to pass my own scope in, as my app has with drive.file, and this Loader should have enough with that also.

**Comment by lkuligin** [comment]
it has been addresssed here, correct?
https://github.com/langchain-ai/langchain-google/pull/424

**Comment by walterheck** [comment]
Indeed, this can be closed. It's handled there.

**Comment by walterheck** [comment]
Could you please publish langchain_google_community 1.0.9? This mistakenly was included in the genai launch, but that's not where this code lives ;)

**Comment by walterheck** [comment]
@lkuligin ping?
