### ISSUE TITLE
Manual assignment of Document IDs in VertexaIVectorStore ignored

### ISSUE THREAD

**Issue by rubenschulze** [langchain-ai/langchain-google#435]
I wanted to create a vector store with manually assigned IDs to the documents, so that the documents saved to google cloud storage and the ids in the vector search index align. Sadly i had to notice some bugs while trying.

When creating `Document` with `langchain_core.documents.Document`, one can pass an `id` to manually set the ID to be used. This should be respected by `VectorSearchVectorStore.add_documents` but this method calls `add_texts` without passing the IDs.
`add_texts` allows passing IDs as part of its `kwargs`, but will generate random IDs anyway.

If anyone knows an intended implemented method to manually set IDs, please let me know!

**Comment by lkuligin** [comment]
it's a good feature to add.
would you be open to send a PR with this improvement?

**Comment by rubenschulze** [comment]
Sure, i will see what i can put together! If you could refer some resources on how to create satisfactory PRs for this repo, will gladly follow their instructions.

**Comment by rubenschulze** [comment]
Please checkout my PR: https://github.com/langchain-ai/langchain-google/pull/467
