### ISSUE TITLE
ChatGoogleGenerativeAI streaming stopping/freezing before completion

### ISSUE THREAD

**Issue by boriswang01** [langchain-ai/langchain-google#436]
occasionally when using ChatGoogleGenerativeAI to stream output, the stream stops or freezes before the stream complete.

**Comment by lkuligin** [comment]
could you provide a reproducible sample, please?

**Comment by boriswang01** [comment]
> could you provide a reproducible sample, please?

Trying to replicate, seems like the only times that the stream stops before completion is when it triggers the safety check system. Is this intended or is it a bug?

**Comment by lkuligin** [comment]
could you provide a reproducible example, please?

**Comment by boriswang01** [comment]
![Uploading Screenshot 2024-08-15 122013.png…]()

here's an example, safety settings is default

**Comment by lkuligin** [comment]
@boriswang01 could you share your prompt as a text, please?

**Comment by boriswang01** [comment]
> @boriswang01 could you share your prompt as a text, please?

prompt: "You are Elon Musk and you're about to unveil the latest innovation from Tesla - a line of humanoid companion robots designed to assist and entertain. However, a prominent tech journalist has just leaked a rumor that these robots may have a "secret" adult mode. How do you respond to this rumor on stage?"
