### ISSUE TITLE
ChatVertexAI hanging

### ISSUE THREAD

**Issue by Layvier** [langchain-ai/langchain-google#438]
Hi,

I've found something weird happening with ChatVertexAI, which I suspect is related to the way the credentials are obtained. I build a model as such, which I then use in a chain:
```
model = ChatVertexAI(model_name="gemini-1.5-pro-001", max_retries=3)

chain = prompt
    | model
    | parser
```

However, this seems to hang randomly when calling the chain in my application, and running the evals on it doesn't work either, it also hangs (always). My `GOOGLE_APPLICATION_CREDENTIALS` env var is well defined.

Weirdly enough, invoking the model directly after instantiating it seems to fix it:

```
model = ChatVertexAI(model_name="gemini-1.5-pro-001", max_retries=3)
print(model.invoke("Hello, how are you?"))
chain = prompt
    | model
    | parser
```
I'm using the version 1.0.8.

Any ideas what the issue could be?

Thanks in advance,
Olivier

**Comment by ccurme** [comment]
@lkuligin any thoughts on this one? Seems related to https://github.com/langchain-ai/langchain-google/issues/436

**Comment by lkuligin** [comment]
@Layvier could you provide a fully reproducible example, please? Most probably the prompt is misconfigured, and it doesn't just hang, it's retrying (what's your log level? are warning printed to the stdout?).
Another thing, if your prompt includes raw pdf documents, then it also might take a while until you get a response :).

**Comment by ccurme** [comment]
Closing for now but will re-open if author gets back with more detail.
