### ISSUE TITLE
Problem running tools using the langchain-google-vertexai package

### ISSUE THREAD

**Issue by moizsajid-securiti** [langchain-ai/langchain-google#46]
Hi there, I am trying to run the code below using the `langchain-google-vertexai` Python package where I want to do function calling using the `gemini-pro` model. But I am getting the following error message `AttributeError: 'dict' object has no attribute 'schema'` at line 22 of the `libs/vertexai/langchain_google_vertexai/functions_utils.py` file when I run code below:

```python
from langchain import hub
from langchain.agents import AgentExecutor, create_openai_functions_agent
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_google_vertexai import ChatVertexAI

tavily_tool = TavilySearchResults(max_results=1)
tools = [tavily_tool]

instructions = """You are an assistant."""
base_prompt = hub.pull("langchain-ai/openai-functions-template")
prompt = base_prompt.partial(instructions=instructions)

llm = ChatVertexAI(model_name="gemini-pro", temperature=0.0, convert_system_message_to_human=True)

agent = create_openai_functions_agent(llm, tools, prompt)

agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

agent_executor.invoke({"input": "what is LangChain?"})
```

Can you please help me resolve this error? The above code runs fine with the `langchain-google-genai` package using `ChatGoogleGenerativeAI` instead of `ChatVertexAI`. Thanks!

**Comment by lkuligin** [comment]
It's hard to help with that, unfortunately, since I don't have a tavily API key.
Could you provide another reproducible example that uses open tools, please? Or Google tools :) since for those I don't have a problem with a key.
