### ISSUE TITLE
ChatVertexAI with_structured_output fails in async mode

### ISSUE THREAD

**Issue by artdent** [langchain-ai/langchain-google#487]
The json-schema tool parser inside `with_structured_output` for ChatVertexAI is defined as follows:

```
parser = JsonOutputToolsParser(first_tool_only=True) | RunnableGenerator(_yield_args)
```

Because the RunnableGenerator is only called with a single argument, it does not support async invocation. Attempting to call `.ainvoke()` on the resulting runnable causes the following error:

```
NotImplementedError('RunnableGenerator(_yield_args) only supports sync methods.')
```

The fix (based on my limited understanding of RunnableGenerator) is to pass an async version of _yield_args as the second argument to the RunnableGenerator.

Versions:
```
langchain-google-vertexai=1.0.8
langchain-core=0.2.38
```

**Comment by strentom** [comment]
@artdent , can you confirm whether this is still broken? I see no error when using async in
```
langchain-core                 0.3.7
langchain-google-vertexai      2.0.3
```
