### ISSUE TITLE
[Feature Request] ChatVertexAI: Support for JSON Schema in .withStructuredOutput Method

### ISSUE THREAD

**Issue by luonghuuthanhnam** [langchain-ai/langchain-google#503]
Currently, the `.withStructuredOutput` method in `ChatVertexAI` only supports the `functionCalling` mechanism. However, Google VertexAI already allows for the use of JSON Schema through model configuration. Are there any plans to support `jsonSchema` in this method?

**Comment by lkuligin** [comment]
You can already use controlled generation with `response_mime_type` parameter.
Or how would you see this?

**Comment by luonghuuthanhnam** [comment]
> You can already use controlled generation with `response_mime_type` parameter. Or how would you see this?
Thank for your reply.
I mean the `response schema`.
`response_mime_type` specifies the format of the response (e.g., JSON, text), while the `response schema` defines the structure and data types expected in the response.
[Ref](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/control-generated-output)
