### ISSUE TITLE
Add llama 3.2 models to model_garden_maas

### ISSUE THREAD

**Issue by jcoyne** [langchain-ai/langchain-google#519]
https://github.com/langchain-ai/langchain-google/blob/main/libs/vertexai/langchain_google_vertexai/model_garden_maas/_base.py#L37C1-L41C2

I'm seeing `Value error, Model meta/llama-3.2-90b-vision-instruct-maas is not supported yet!` when attempting to use https://console.cloud.google.com/vertex-ai/publishers/meta/model-garden/llama-3.2-90b-vision-instruct-maas

**Comment by lkuligin** [comment]
Would like to work on this feature?
