### ISSUE TITLE
Add support for AvgLogprobs to VertexAI integrations

### ISSUE THREAD

**Issue by jaymon0703** [langchain-ai/langchain-google#525]
Hi LangChain Team!

Can we please add support for returning AvgLogprobs from calls to VertexAI models please?

Thank you!

Regards
Jasen

**Comment by lkuligin** [comment]
would you be open to send a PR, please?

**Comment by jaymon0703** [comment]
Thank you!

**Comment by jaymon0703** [comment]
Hi @jzaldi @lkuligin i think this change might be incomplete in that the [`avg_logprobs` property was added to the `Candidate` class in `vertexai`](https://github.com/googleapis/python-aiplatform/blob/2cef97f31bf4d0410c76b73da03805120605ef0c/vertexai/generative_models/_generative_models.py#L2320) but it does not appear as if you import this class in [chat_models.py](https://github.com/langchain-ai/langchain-google/blob/af44de36cb82277bb5e535e6c2ba968c5b52a18d/libs/vertexai/langchain_google_vertexai/chat_models.py#L73) in `langchain-google/libs/vertexai/langchain_google_vertexai`
