### ISSUE TITLE
 GCSDirectoryLoader not able to load pdf documents from GCS bucket

### ISSUE THREAD

**Issue by Mona19** [langchain-ai/langchain-google#597]
Trying to load pdf files using below code
%pip install --upgrade --quiet  langchain-google-community[gcs]
!apt-get install poppler-utils
from langchain_google_community import GCSDirectoryLoader

loader = GCSDirectoryLoader(project_name=PROJECT_ID, bucket=bucket_name) 
documents = loader.load()

Getting exception at loader.load()  method.
--------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-9-129e45e8d6d5>](https://localhost:8080/#) in <cell line: 4>()
      2 bucket_name="nasa_resaerch_paper"
      3 loader = GCSDirectoryLoader(project_name=PROJECT_ID, bucket=bucket_name)  # Load *only* the specified file with prefix
----> 4 documents = loader.load()
      5 

22 frames
[/usr/local/lib/python3.10/dist-packages/nltk/data.py](https://localhost:8080/#) in __init__(self, _path)
    310         _path = os.path.abspath(_path)
    311         if not os.path.exists(_path):
--> 312             raise OSError("No such file or directory: %r" % _path)
    313         self._path = _path
    314 

OSError: No such file or directory: '/root/nltk_data/tokenizers/punkt/PY3_tab'

**Comment by lkuligin** [comment]
afaik, you need to install nltk or you need to override the pdf parser you're using
